title: Whisper Wild
description: Sensory-friendly grooming tools
theme: minima
# Build settings
markdown: kramdown
permalink: pretty

# Collections for structured pages (optional but handy)
collections:
  pages:
    output: true
  products:
    output: true

# Navigation (we’ll read from _data/nav.yml)
defaults:
  - scope: {path: "", type: "pages"}
    values: {layout: default}
  - scope: {path: "", type: "products"}
    values: {layout: product}
